Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Slipstream: true

  Flow:
    http:
      middlewares:
        slipstream:
          position: 'before dispatch'
          middleware: 'Sitegeist\Slipstream\Middleware\SlipstreamMiddleware'

Sitegeist:
  Slipstream:
    debugMode: false

